### ISSUE TITLE
Focus le champ de recherche lors de l'ouverture d'un onglet

### ISSUE THREAD

**Issue by BLeger** [Feldrise/SieloNavigateur#14]
Quand on ouvre un onglet, c'est souvent pour rechercher quelque chose ou copier une URL. C'est donc plus rapide si on a pas besoin de sélectionner manuellement la barre de recherche

**Comment by Feldrise** [comment]
Merci beaucoup ! Sur la base de ta suggestion j'ai créé un nouveau comportement lors de l'ouverture d'un nouvel onglet. Fait donc au commit [29c573c](https://github.com/Feldrise/SieloNavigateur/commit/29c573ce8ba1ddb80c3b4b319894f3ad92f0eb38) !
