### ISSUE TITLE
Donation and contact links 

### ISSUE THREAD

**Issue by BLeger** [Feldrise/SieloNavigateur#19]
In the "Help Us" and "About Sielo" pop up, the lack of contrast between the links and the background makes them almost impossible to read, at least on my screen.

Screenshot : [https://i.imgur.com/VB3kmbA.png](url)

Moreover, the donation links doesn't work for me, I can click on it but nothing happens

**Comment by Feldrise** [comment]
You are right! Actually, links are not oppened, but they are working if you copy/past theme :wink: (should be fixed as well anyway)

**Comment by Feldrise** [comment]
Thanks a lot, it is definitely fixed in the commit [bb62c97](https://github.com/Feldrise/SieloNavigateur/commit/bb62c977685438fe2dbd7f05e5bbbd965016e0b7)
