### ISSUE TITLE
adblock breaks everything

### ISSUE THREAD

**Issue by EdFrost** [Feldrise/SieloNavigateur#2]
;-; i want my ads to be gone... like poof gone

**Comment by Feldrise** [comment]
For now, we will remove adblock. AdBlock will stay in the code, but you should wait an extension. Sielo already support extensions so if you know someone interrested to make an adblock we are interrested.

**Comment by Feldrise** [comment]
The issue seems to be fixed with the fix of AdBlock! Thanks for your feedback.
