### ISSUE TITLE
Compiler documentation

### ISSUE THREAD

**Issue by Dregni** [Feldrise/SieloNavigateur#26]
There isn't a usage or --help ( or -h)
for the sielo-compiler

**Comment by Feldrise** [comment]
It's true, I never thought about that...

**Comment by Feldrise** [comment]
I concidere it has a bug, will be fixed soon.

**Comment by Dregni** [comment]
It's a classical Minimal Viable Product when starting a project tho

**Comment by Feldrise** [comment]
I was young when I started Sielo, I learned so many things from it :wink:

**Comment by Feldrise** [comment]
The "help" argument has been added in this commit [461b354](https://github.com/Feldrise/SieloNavigateur/commit/461b354bcbb295d2f576d2017a00dfa9b8f8ba0e).
Thanks for the issue !
