### ISSUE TITLE
Changer les "floating button"

### ISSUE THREAD

**Issue by jusdepatate** [Feldrise/SieloNavigateur#27]
https://xen.owns-this.site/281c7a7c.png
tu devrais changer tout les "floating button" par l'action que chaque bouton fait

**Comment by Feldrise** [comment]
Tu as raison, je considère ça comme un bug. À corriger ^^

**Comment by Feldrise** [comment]
Corrigé dans le commit [67fb2ef](https://github.com/Feldrise/SieloNavigateur/commit/67fb2ef5e0b45ed80f82a41716484ca6e8b789e8). Arrive donc pour l'OB 9.
